### ISSUE TITLE
[BUG] httpx dependency is not pinned

### ISSUE THREAD

**Issue by StevenReitsma** [python-rt/python-rt#102]
**Describe the bug**
The `httpx` library was [updated 4 days ago](https://github.com/encode/httpx/releases/tag/0.28.0), removing the `proxies` argument of the `Client.__init__` constructor. This argument is used by python-rt and causes the library to error when instantiating the `rt.rest2.Rt` object.

**To Reproduce**
1. Instantiate the `rt.rest2.Rt` object.

Error:
```
>       self.session = httpx.Client(timeout=http_timeout, verify=verify_cert, proxies=proxy, auth=http_auth)
E       TypeError: Client.__init__() got an unexpected keyword argument 'proxies'
```

https://github.com/python-rt/python-rt/blob/master/rt/rest2.py#L127

**Expected behavior**
Please pin the `httpx` library in the dependencies to a version that works with RT ([httpx 0.27.2](https://github.com/encode/httpx/releases/tag/0.27.2)).
Eventually, the RT library should upgrade to httpx 0.28.0, but this requires code changes, removing the use of the deprecated `proxies` argument.

**Environment (please complete the following information):**
 - Python version: 3.11.x
 - python-rt version: 3.3.1

**Comment by StevenReitsma** [comment]
See #103 for fix

**Comment by sim0nx** [comment]
Thanks for the report. Though I do agree that the library should be pinned to some extent, that would not have prevented this issue as the breaking change was introduced in a minor version. I do not intend to pin httpx to a specific version as libraries should not do that. That would created other headaches on apps using the library and possibly requiring a more recent version.

Could you please give #105 a try?

**Comment by StevenReitsma** [comment]
Thanks for the quick fix!
